name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd 2-ticketing/payments && npm install && npm run test:ci
