name: tests-orders

on:
  pull_request:
    paths:
      - "2-ticketing/orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd 2-ticketing/orders && npm install && npm run test:ci
